# Config for Dependabot updates. See Documentation here:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Update GitHub actions in workflows
  - package-ecosystem: 'github-actions'
    directory: '/'
    # Every weekday
    schedule:
      interval: 'daily'

  # Enable version updates for Docker
  # We need to specify each Dockerfile in a separate entry because Dependabot doesn't
  # support wildcards or recursively checking subdirectories. Check this issue for updates:
  # https://github.com/dependabot/dependabot-core/issues/2178
  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/local/django` directory
    directory: 'compose/local/django/'
    # Every weekday
    schedule:
      interval: 'daily'
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/local/docs` directory
    directory: 'compose/local/docs/'
    # Every weekday
    schedule:
      interval: 'daily'
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/local/node` directory
    directory: 'compose/local/nuxt/'
    # Every weekday
    schedule:
      interval: 'daily'
    # Ignore major version updates (18 -> 20)
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'

  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/production/aws` directory
    directory: 'compose/local/traefik/'
    # Every weekday
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/production/django` directory
    directory: 'compose/production/django/'
    # Every weekday
    schedule:
      interval: 'daily'
    # Ignore minor version updates (3.10 -> 3.11) but update patch versions
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-minor'

  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/production/postgres` directory
    directory: 'compose/production/postgres/'
    # Every weekday
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/production/traefik` directory
    directory: 'compose/production/traefik/'
    # Every weekday
    schedule:
      interval: 'daily'

  - package-ecosystem: 'docker'
    # Look for a `Dockerfile` in the `compose/production/traefik` directory
    directory: 'compose/production/nuxt-ssr/'
    # Every weekday
    schedule:
      interval: 'daily'
    # Ignore major version updates (18 -> 20)
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'

  # Enable version updates for Python/Pip - Production
  - package-ecosystem: 'pip'
    # Look for a `requirements.txt` in the `root` directory
    # also 'setup.cfg', 'runtime.txt' and 'requirements/*.txt'
    directory: '/backend'
    # Every weekday
    schedule:
      interval: 'daily'

  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/frontend"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
    # If don't need to update from 18 to 20
    # ignore:
    #   - dependency-name: '@types/node'
    #     update-types:
    #       - 'version-update:semver-major'
    #       - 'version-update:semver-minor'
    #       - 'version-update:semver-patch'
